### ISSUE TITLE
Error when using headers flag

### ISSUE THREAD

**Issue by copy-and-paste** [s0md3v/Corsy#20]
When using the headers flag, we get the following error

```
Traceback (most recent call last):
  File "corsy.py", line 46, in <module>
    header_dict = extractHeaders(header_dict)
NameError: name 'extractHeaders' is not defined
```
The following command was used

```python3 corsy.py -u https://accf1f791f8593a380326bad001f00ac.web-security-academy.net/accountDetails --headers "session=JhpVqwyzs4Q"```

**Comment by s0md3v** [comment]
Fixed.
