### ISSUE TITLE
error on add header

### ISSUE THREAD

**Issue by dimax0220** [s0md3v/Corsy#24]
corsy.py -u https://www.example.com/api/company/memberships --headers "Cookie: Token=sco3FjPRZpS"

    ＣＯＲＳＹ  {v1.0-beta}

Traceback (most recent call last):
  File "corsy.py", line 46, in <module>
    header_dict = extractHeaders(header_dict)
NameError: name 'extractHeaders' is not defined

**Comment by s0md3v** [comment]
Fixed.
