### ISSUE TITLE
name 'extractHeaders' is not defined

### ISSUE THREAD

**Issue by justlife4x4** [s0md3v/Corsy#25]
I ran the following command:
## Command:
```python3 corsy.py -u https://somesitre --headers "Cookie: somecookie Connection: close"```
## Got the following error:
```

    ＣＯＲＳＹ  {v1.0-beta}

Traceback (most recent call last):
  File "corsy.py", line 46, in <module>
    header_dict = extractHeaders(header_dict)
NameError: name 'extractHeaders' is not defined
```
I'm not soo good in python ..hope u can help me 👍

**Comment by ecdeveloper** [comment]
At the top of `corsy.py` add `extractHeaders` to import from core.utils: 

```from core.utils import host, prompt, format_result, create_url_list, extractHeaders```
