### ISSUE TITLE
More third parties to be checked

### ISSUE THREAD

**Issue by sC-AA** [s0md3v/Corsy#5]
Please consider checking whether those third parties are allowed:

1. https://whatever.github.io
2. https://jsbin.com
3. https://codepen.io
4. https://s.codepen.io
5. https://jsfiddle.net
6. https://fiddle.jshell.net
7. http://www.webdevout.net
8. https://repl.it

**Comment by s0md3v** [comment]
It checks for any third party host.

Here's the pseudo-code

```
If acao_header_host != input_host:
    return "third party allowed"
```
