### ISSUE TITLE
Documentation of requirements

### ISSUE THREAD

**Issue by davidsneighbour** [s0md3v/Corsy#6]
Please add a section to the README on how to install requirements for the less pythony people :)

I know it should be `pip install -r requirements.txt`, but maybe others don't. 

Also, on running the script another module is not found:

```
python corsy.py -u https://samui-samui.de
Traceback (most recent call last):
  File "corsy.py", line 6, in <module>
    from core.utils import load_json, host
ImportError: No module named core.utils
```

What librar(y|ies) am I missing?

**Comment by davidsneighbour** [comment]
I had to do the following things to get it running:

- use python3 (Ubuntu's default is set to 2)
- install `python3-tld` library via apt. 

After that it worked.

**Comment by s0md3v** [comment]
The project includes a `requirements.txt` file as per community standards. It contains the only two Python libraries you need to install to run Corsy.

**Comment by davidsneighbour** [comment]
Sorry, but "community standards" define the format of requirements.txt, not the fact that you could document the preparation of the system ("run `pip3 install -r requirements.txt`") and also not the fact that you should note which version of python has to be used. On Python version 2.7 and below the script does not work as is described in the initial bug note. Python 2.7 is installed on most Ubuntu-based systems per default.

If you don't want real-life usage of your program then don't document these things, sure. The problem is, I, for instance, came via a short notice on a mailing list for people that are typically not Python user and assumed your program is for people who want to secure their domain setup, not for python programmers.
