### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by vdvcoder** [s0md3v/Corsy#7]
Hi,
When i try to run the corsy.py i got following error.

```
Traceback (most recent call last):
  File "corsy.py", line 6, in <module>
    from core.utils import load_json, host
ModuleNotFoundError: No module named 'core.utils
```

Python version: Python 3.7.5

**Comment by s0md3v** [comment]
Are you sure you ran the script with `python3` not `python`?

**Comment by vdvcoder** [comment]
Yes, i run it with: `python3 corsy.py -u http://url.be`

![vmplayer_T1vA3nXRs1](https://user-images.githubusercontent.com/13916116/69706977-1a28bd00-10f9-11ea-842e-d69f8cb834eb.png)

**Comment by s0md3v** [comment]
The latest commit should have fixed it.
Please re-clone and see if the issue still exists.
